# Jekyll Config


port: 1337
# host: 0.0.0.0
url: "https://benjic.xyz"
theme-color: "#673ab7"
twitter: "@MindfulMinun"
synopsis: >
    I like coding things for the Internet & playing the piano.
    I’m also on [Twitter](https://twitter.com/MindfulMinun)
    and [GitHub](https://github.com/mindfulminun). Come say hi!

timezone: America/Chicago
permalink: /:year-:month-:day/:categories/:title/

#! My vars
tracking-id: "UA-113187497-1"

plugins:
    - jekyll-coffeescript
    - jekyll-autoprefixer
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-minifier

#! Plugin vars
include:
    - ".htaccess"
# Markdown parsing
# markdown:    redcarpet
# highlighter: rouge
# redcarpet:
#   extensions: []

jekyll-minifier:
    exclude:
        - 'robots.txt'
        - 'sitemap.xml'
        - '.htaccess'

# Sass settings
sass:
    sass_dir: _sass
    style: compressed

autoprefixer:
    browsers:
        - last 2 versions

# Frontmatter defaults
defaults:
    -
        scope:
            path: "" # Scope: All files...
            type: "pages" # ...that are pages, so no JS files, for example
        values:
            # layout: default
            theme-color: "#673ab7"
            manifest: "/manifest.json"
    -
        # This is here because Jekyll isn't smart enough to not set a layout for JS files, but doesn't for SCSS files????????
        scope:
            path: "scripts"
        values:
            layout: none
    -
        scope:
            path: "_posts"
        values:
            layout: "default"
            theme-color: "#673ab7"
