#! ========================================
# Jekyll Config

port: 1337
# host: 0.0.0.0
url: "https://benjic.xyz"
theme-color: "#448aff"
twitter: "@MindfulMinun"
synopsis: >
    I like coding things for the Internet & playing the piano.
    I’m also on [Twitter](https://twitter.com/MindfulMinun)
    and [CodePen](https://codepen.io/MindfulMinun).
    Feel free to say hi.

timezone: America/Chicago
permalink: /:year-:month-:day/:categories/:title/
markdown: kramdown

#! ========================================
#! My vars
tracking-id: "UA-113187497-1"

#! See Gemfile
plugins:
    - jekyll-autoprefixer
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-minifier
    - jekyll-coffeescript

#! ========================================
#! Plugin vars
# include:
#     - ".htaccess"
# show_drafts: true
# incremental: true
strict_front_matter: true
exclude:
    - "_archives/"

jekyll-minifier:
    exclude:
        - "robots.txt"
        - "sitemap.xml"
        - ".htaccess"
        - "mocha/*"

#! ========================================
# Sass settings
sass:
    sass_dir: _sass
    style: compressed

autoprefixer:
    browsers:
        - last 2 versions

#! ========================================
# Frontmatter defaults
defaults:
    -
        scope:
            path: "" # Scope: All files...
            type: "pages" # ...that are pages, so no JS files, for example
        values:
            # layout: default
            theme-color: "#448aff"
            # manifest: "/manifest.json"
    -
        # This is here because Jekyll isn't smart enough to not set a layout for JS files, but doesn't for SCSS files?¿??¿¿¿??
        scope:
            path: "scripts"
        values:
            layout: none
    -
        scope:
            path: "_posts"
        values:
            layout: "default"
            theme-color: "#448aff"
    -
        scope:
            path: "mocha/*"
        values:
            sitemap: false
